type hrtime = int64

module Nvlist = struct
  type t

  type encoding =
    | Native
    | XDR

  external alloc : unit -> t = "caml_nvlist_alloc"
  external pack : t -> encoding -> bytes = "caml_nvlist_pack"
  external unpack : bytes -> t = "caml_nvlist_unpack"
  external dup : t -> t = "caml_nvlist_dup"
  external merge : t -> t -> t = "caml_nvlist_merge"
  external add_boolean : t -> string -> unit = "caml_nvlist_add_boolean"
  external add_boolean_value : t -> string -> bool -> unit = "caml_nvlist_add_boolean_value"
  external add_byte : t -> string -> int -> unit = "caml_nvlist_add_byte"
  external add_int8 : t -> string -> int -> unit = "caml_nvlist_add_int8"
  external add_uint8 : t -> string -> int -> unit = "caml_nvlist_add_uint8"
  external add_int16 : t -> string -> int -> unit = "caml_nvlist_add_int16"
  external add_uint16 : t -> string -> int -> unit = "caml_nvlist_add_uint16"
  external add_int32 : t -> string -> int32 -> unit = "caml_nvlist_add_int32"
  external add_uint32 : t -> string -> int32 -> unit = "caml_nvlist_add_uint32"
  external add_int64 : t -> string -> int64 -> unit = "caml_nvlist_add_int64"
  external add_uint64 : t -> string -> int64 -> unit = "caml_nvlist_add_uint64"
  external add_string : t -> string -> string -> unit = "caml_nvlist_add_string"
  external add_nvlist : t -> string -> t -> unit = "caml_nvlist_add_nvlist"
  external add_boolean_array : t -> string -> bool array -> unit = "caml_nvlist_add_boolean_array"
  external add_byte_array : t -> string -> bytes -> unit = "caml_nvlist_add_byte_array"
  external add_int8_array : t -> string -> int array -> unit = "caml_nvlist_add_int8_array"
  external add_uint8_array : t -> string -> int array -> unit = "caml_nvlist_add_uint8_array"
  external add_int16_array : t -> string -> int array -> unit = "caml_nvlist_add_int16_array"
  external add_uint16_array : t -> string -> int array -> unit = "caml_nvlist_add_uint16_array"
  external add_int32_array : t -> string -> int32 array -> unit = "caml_nvlist_add_int32_array"
  external add_uint32_array : t -> string -> int32 array -> unit = "caml_nvlist_add_uint32_array"
  external add_int64_array : t -> string -> int64 array -> unit = "caml_nvlist_add_int64_array"
  external add_uint64_array : t -> string -> int64 array -> unit = "caml_nvlist_add_uint64_array"
  external add_string_array : t -> string -> string array -> unit = "caml_nvlist_add_string_array"
  external add_nvlist_array : t -> string -> t array -> unit = "caml_nvlist_add_nvlist_array"
  external add_hrtime : t -> string -> hrtime -> unit = "caml_nvlist_add_hrtime"
  external add_double : t -> string -> float -> unit = "caml_nvlist_add_double"
  external remove : t -> string -> unit = "caml_nvlist_remove"
  external lookup_boolean : t -> string -> bool option = "caml_nvlist_lookup_boolean"
  external lookup_boolean_value : t -> string -> bool option = "caml_nvlist_lookup_boolean_value"
  external lookup_byte : t -> string -> int option = "caml_nvlist_lookup_byte"
  external lookup_int8 : t -> string -> int option = "caml_nvlist_lookup_int8"
  external lookup_uint8 : t -> string -> int option = "caml_nvlist_lookup_uint8"
  external lookup_int16 : t -> string -> int option = "caml_nvlist_lookup_int16"
  external lookup_uint16 : t -> string -> int option = "caml_nvlist_lookup_uint16"
  external lookup_int32 : t -> string -> int32 option = "caml_nvlist_lookup_int32"
  external lookup_uint32 : t -> string -> int32 option = "caml_nvlist_lookup_uint32"
  external lookup_int64 : t -> string -> int64 option = "caml_nvlist_lookup_int64"
  external lookup_uint64 : t -> string -> int64 option = "caml_nvlist_lookup_uint64"
  external lookup_string : t -> string -> string option = "caml_nvlist_lookup_string"
  external lookup_nvlist : t -> string -> t option = "caml_nvlist_lookup_nvlist"
  external lookup_boolean_array : t -> string -> bool array option = "caml_nvlist_lookup_boolean_array"
  external lookup_byte_array : t -> string -> bytes option = "caml_nvlist_lookup_byte_array"
  external lookup_int8_array : t -> string -> int array option = "caml_nvlist_lookup_int8_array"
  external lookup_uint8_array : t -> string -> int array option = "caml_nvlist_lookup_uint8_array"
  external lookup_int16_array : t -> string -> int array option = "caml_nvlist_lookup_int16_array"
  external lookup_uint16_array : t -> string -> int array option = "caml_nvlist_lookup_uint16_array"
  external lookup_int32_array : t -> string -> int32 array option = "caml_nvlist_lookup_int32_array"
  external lookup_uint32_array : t -> string -> int32 array option = "caml_nvlist_lookup_uint32_array"
  external lookup_int64_array : t -> string -> int64 array option = "caml_nvlist_lookup_int64_array"
  external lookup_uint64_array : t -> string -> int64 array option = "caml_nvlist_lookup_uint64_array"
  external lookup_string_array : t -> string -> string array option = "caml_nvlist_lookup_string_array"
  external lookup_nvlist_array : t -> string -> t array option = "caml_nvlist_lookup_nvlist_array"
  external lookup_hrtime : t -> string -> hrtime option = "caml_nvlist_lookup_hrtime"
  external lookup_double : t -> string -> float option = "caml_nvlist_lookup_double"
  external exists : t -> string -> bool = "caml_nvlist_exists"
  external empty : t -> bool = "caml_nvlist_empty"
end
